services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glycemic_map_api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
    - "${API_PORT}:${API_PORT}"
    env_file:
    - .env
    depends_on:
      - db
    networks:
      - glycemic_net
    restart: unless-stopped
  
  db:
    image: postgres:latest
    container_name: glycemic_map_database
    volumes:
      - ./src/db/migrations/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    networks:
      - glycemic_net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  glycemic_net:
    external: true